//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 10:46:59 AM IST 
//


package com.oab.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oab.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReplyDate_QNAME = new QName("http://www.oab.com/Response", "replyDate");
    private final static QName _TransactionReference_QNAME = new QName("http://www.oab.com/Response", "transactionReference");
    private final static QName _Workstation_QNAME = new QName("http://www.oab.com/Response", "workstation");
    private final static QName _ChannelReserved_QNAME = new QName("http://www.oab.com/Response", "channelReserved");
    private final static QName _Channel_QNAME = new QName("http://www.oab.com/Response", "channel");
    private final static QName _TransactionDate_QNAME = new QName("http://www.oab.com/Response", "transactionDate");
    private final static QName _TransactionTime_QNAME = new QName("http://www.oab.com/Response", "transactionTime");
    private final static QName _ReplyTime_QNAME = new QName("http://www.oab.com/Response", "replyTime");
    private final static QName _Reference_QNAME = new QName("http://www.oab.com/Response", "reference");
    private final static QName _ReplyStatus_QNAME = new QName("http://www.oab.com/Response", "replyStatus");
    private final static QName _User_QNAME = new QName("http://www.oab.com/Response", "user");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oab.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link FinancialTransaction }
     * 
     */
    public FinancialTransaction createFinancialTransaction() {
        return new FinancialTransaction();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Reply }
     * 
     */
    public Reply createReply() {
        return new Reply();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "replyDate")
    public JAXBElement<String> createReplyDate(String value) {
        return new JAXBElement<String>(_ReplyDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "transactionReference")
    public JAXBElement<String> createTransactionReference(String value) {
        return new JAXBElement<String>(_TransactionReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "workstation")
    public JAXBElement<String> createWorkstation(String value) {
        return new JAXBElement<String>(_Workstation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "channelReserved")
    public JAXBElement<String> createChannelReserved(String value) {
        return new JAXBElement<String>(_ChannelReserved_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "channel")
    public JAXBElement<String> createChannel(String value) {
        return new JAXBElement<String>(_Channel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "transactionDate")
    public JAXBElement<String> createTransactionDate(String value) {
        return new JAXBElement<String>(_TransactionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "transactionTime")
    public JAXBElement<String> createTransactionTime(String value) {
        return new JAXBElement<String>(_TransactionTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "replyTime")
    public JAXBElement<String> createReplyTime(String value) {
        return new JAXBElement<String>(_ReplyTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "reference")
    public JAXBElement<String> createReference(String value) {
        return new JAXBElement<String>(_Reference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "replyStatus")
    public JAXBElement<String> createReplyStatus(String value) {
        return new JAXBElement<String>(_ReplyStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/Response", name = "user")
    public JAXBElement<String> createUser(String value) {
        return new JAXBElement<String>(_User_QNAME, String.class, null, value);
    }

}
