//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 06:08:10 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(/*namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.06",*/ elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns= {
        @XmlNs(prefix="ns2", namespaceURI="http://www.Progressoft.com/ACH")})
package iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.annotation.XmlNs;
