//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 11:49:45 AM IST 
//


package com.oab.doubleentryrequest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oab.doubleentryrequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Currency_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "currency");
    private final static QName _TransactionTime_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "transactionTime");
    private final static QName _ChannelReserved_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "channelReserved");
    private final static QName _Channel_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "channel");
    private final static QName _Account_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "account");
    private final static QName _User_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "user");
    private final static QName _TransactionDate_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "transactionDate");
    private final static QName _Workstation_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "workstation");
    private final static QName _TransactionReference_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "transactionReference");
    private final static QName _Amount_QNAME = new QName("http://www.oab.com/doubleEntryRequest", "amount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oab.doubleentryrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link DoubleEntryFinancialTransaction }
     * 
     */
    public DoubleEntryFinancialTransaction createDoubleEntryFinancialTransaction() {
        return new DoubleEntryFinancialTransaction();
    }

    /**
     * Create an instance of {@link Debit }
     * 
     */
    public Debit createDebit() {
        return new Debit();
    }

    /**
     * Create an instance of {@link Credit }
     * 
     */
    public Credit createCredit() {
        return new Credit();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "transactionTime")
    public JAXBElement<String> createTransactionTime(String value) {
        return new JAXBElement<String>(_TransactionTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "channelReserved")
    public JAXBElement<String> createChannelReserved(String value) {
        return new JAXBElement<String>(_ChannelReserved_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "channel")
    public JAXBElement<String> createChannel(String value) {
        return new JAXBElement<String>(_Channel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "account")
    public JAXBElement<String> createAccount(String value) {
        return new JAXBElement<String>(_Account_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "user")
    public JAXBElement<String> createUser(String value) {
        return new JAXBElement<String>(_User_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "transactionDate")
    public JAXBElement<String> createTransactionDate(String value) {
        return new JAXBElement<String>(_TransactionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "workstation")
    public JAXBElement<String> createWorkstation(String value) {
        return new JAXBElement<String>(_Workstation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "transactionReference")
    public JAXBElement<String> createTransactionReference(String value) {
        return new JAXBElement<String>(_TransactionReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oab.com/doubleEntryRequest", name = "amount")
    public JAXBElement<String> createAmount(String value) {
        return new JAXBElement<String>(_Amount_QNAME, String.class, null, value);
    }

}
